
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gomez
 */
public class Ventana extends javax.swing.JFrame {
    
    private Timer tiempo;
    private int centesimaSegundos, segundos, minutos, horas;

    public Ventana() {
        initComponents();
        añadirFondo();
        
        iniciarBotones(false);
        
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        tiempo = new Timer (10,accion);
        
    }
    

    private ActionListener accion = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundos++;
            if (centesimaSegundos>99){
                centesimaSegundos=0;
                segundos++;
            }
            if (segundos >59){
                segundos=0;
                minutos++;
            }
            if (minutos>59){
                minutos=0;
                horas++;
            }
            
            modificarEtiquetaTiempo();
        }
    };
    
    private void añadirFondo(){
        final ImageIcon fondo = new ImageIcon(getClass().getResource("/Imagenes/images.jpeg"));
        etiquetaFondo.setIcon(new ImageIcon(fondo.getImage().getScaledInstance(etiquetaFondo.getWidth(), etiquetaFondo.getHeight(), Image.SCALE_SMOOTH)));
    }
    
    private void modificarEtiquetaTiempo(){
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimaSegundos<=9?"0":"")+centesimaSegundos; 
        etiquetaTiempo.setText(texto);
    }
    
    private void iniciarBotones(boolean a){
        botonStop.setEnabled(a);
        botonRestart.setEnabled(a);
        if (a==true){
            botonStart.setEnabled(false);
        }else{
            botonStart.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaTiempo = new javax.swing.JLabel();
        etiquetaCronometro = new javax.swing.JLabel();
        botonRestart = new javax.swing.JButton();
        botonStart = new javax.swing.JButton();
        botonStop = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTiempo.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        etiquetaTiempo.setText("00:00:00:00");
        jPanel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 50));

        etiquetaCronometro.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        etiquetaCronometro.setText("CRONÓMETRO: ");
        jPanel1.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        botonRestart.setText("Reiniciar");
        botonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestartActionPerformed(evt);
            }
        });
        jPanel1.add(botonRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 40));

        botonStart.setText("Iniciar");
        botonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStartActionPerformed(evt);
            }
        });
        jPanel1.add(botonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, 40));

        botonStop.setText("Pausar");
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        jPanel1.add(botonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 40));
        jPanel1.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestartActionPerformed
        // TODO add your handling code here:
        tiempo.stop();
        centesimaSegundos=0;
        segundos=0;
        minutos=0;
        horas=0;
        
        modificarEtiquetaTiempo();
        botonStart.setText("Iniciar");
        iniciarBotones(false);
    }//GEN-LAST:event_botonRestartActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        // TODO add your handling code here:
        tiempo.stop();
        botonStart.setEnabled(true);
        botonStop.setEnabled(false);
    }//GEN-LAST:event_botonStopActionPerformed

    private void botonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStartActionPerformed
        // TODO add your handling code here:
        tiempo.start();
        
        botonStart.setText("Reanudar");
        iniciarBotones(true);

            

        
    }//GEN-LAST:event_botonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRestart;
    private javax.swing.JButton botonStart;
    private javax.swing.JButton botonStop;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
